### ISSUE TITLE
Fix Triangular shaped AdExp waveform snippets.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit_opt#35]
Instead of stretching and distorting waveforms vertically, by making V_peak a gene-opt parameter,
more natural shapes would likely come from offsetting the vm calculation like [here](https://github.com/russelljjarvis/neuronunit_opt/blob/master/neuronunit/models/backends/bhh.py#L114), but applied [here](https://github.com/russelljjarvis/neuronunit_opt/blob/master/neuronunit/models/backends/badexp.py#L198)

![image](https://user-images.githubusercontent.com/7786645/69467032-809c9b00-0dda-11ea-9cad-9dc295ce4e87.png)

**Comment by rgerkin** [comment]
How is it done now?  Just automatically set the peak to +60 mV?  I think it will still look awkward no matter what the peak value, and since the model itself has no content above the threshold (which is much, much, lower), this is really just for cosmetic value.

**Comment by russelljjarvis** [comment]
The peak is a variable parameter varied by genes. The application of the peak is consistent with what you describe.
https://github.com/russelljjarvis/neuronunit_opt/blob/master/neuronunit/models/backends/badexp.py#L203-L219
