### ISSUE TITLE
A document Notice to debug set PARALLEL_CONFIDENT=False

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit_opt#36]
A piece of documentation. No action required 
@rgerkin 
Many methods inside the file optimization_management.py cannot be easily monkey patched using ```pdb.set_trace()``` unless at the top of the file, the parallel_confident static variable is declared false
``` python
PARALLEL_CONFIDENT=False
```

This converts parallel mapping functions to serial mapping functions. scheduled Parallel mapping functions cannot tolerate being paused, serial ones can.

**Comment by rgerkin** [comment]
Good to know, thank you!

**Comment by russelljjarvis** [comment]
Another Documentation note.

if you are using linux and you have ```apt-get install gnuplot``` and ```pip install asciiplot```

When running from the terminal, you can get very fast memory friendly and disposable ascii plots of waveforms as the GA explores them. The experience is a lot like watching an animation.

Example below:

**Comment by russelljjarvis** [comment]
The effect is like watching this:
https://www.youtube.com/watch?v=FKbarpAlBkw
but for model `vm`s.

I am actually thinking of storing the ascii plots and making an animation to help people understand this work.

**Comment by rgerkin** [comment]
Does this work for parallel execution, too, or only serial GA?

**Comment by russelljjarvis** [comment]
Both.

**Comment by russelljjarvis** [comment]
The fact that the ascii plot is issued at the backend level, means that it executes for all current_injections (passive tests, active tests) automatically.

**Comment by russelljjarvis** [comment]
It's been a stable feature for months, i just never got around to mentioning it.

**Comment by russelljjarvis** [comment]
Actually the video would be better if the ascii plots where snippets.
