### ISSUE TITLE
rename nested neuronunit directory src, to be consistent with other repo structures?

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit_opt#37]
@rgerkin

**Comment by rgerkin** [comment]
I often see this pattern for projects in other language (C, Java, etc.), but usually for Python I see the name of the directory as the intended name of the package.  For example, for http://github.com/numpy/numpy, the package numpy is in the directory numpy and not src (which I don't think it has).  This makes it easier to just directly import the package from that top-level directory (even without installing it, as long as the requirements are already met).  And if you call it "src", I think you have to configure setup.py to install the package in "src" as the desired name of the package, e.g. "neuronunit".

Or maybe you are talking about having the package "neuronunit" be one level below the directory 
"src" (which is in turn one level below repo root)?  

Is there a set of repos you were referring to that you use the pattern for Python packages?

**Comment by russelljjarvis** [comment]
AOK. That makes sense. 

I see it in Julia too, and yes I think there are one or two python packages with src is the nested directory, but I think you are right that it's not a real python convention.
